-- CachyOS Hyprland Configuration

require("config.animations")
require("config.autostart")
require("config.clamshell")
require("config.colors")
require("config.decorations")
require("config.defaults")
require("config.environment")
require("config.hardware_cursor")
require("config.input")
require("config.keybinds")
require("config.misc")
require("config.monitors")
require("config.windowrules")
require("config.workspaces")
